# -*- coding: utf-8 -*-
"""KlasifikasiGambarHewan-Rendy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VHGAl5J0HOqkphFY9EUt4RyoHioiOs7b

# Proyek Klasifikasi Gambar: Animals-10
- **Nama:** Rendy Vallentino
- **NIM:** 8030230050

## 1. Import Semua Packages/Library yang Digunakan
"""

# Install dependencies
!pip install -q tensorflowjs split-folders

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization, GlobalAveragePooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
import numpy as np
import matplotlib.pyplot as plt
import os
import shutil
import zipfile
import splitfolders

print(f"TensorFlow version: {tf.__version__}")
print(f"GPU Available: {tf.config.list_physical_devices('GPU')}")

"""## 2. Data Preparation

### Data Loading
"""

# Setup Kaggle API
from google.colab import files

# Upload kaggle.json
print("Upload file kaggle.json Anda:")
uploaded = files.upload()

# Configure Kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Download Animals-10 dataset dari Kaggle
!kaggle datasets download -d alessiocorrado99/animals10

# Extract dataset
with zipfile.ZipFile('animals10.zip', 'r') as zip_ref:
    zip_ref.extractall('dataset_raw')

print("Dataset berhasil diextract!")

import os

raw_dir = 'dataset_raw/raw-img'

# Filter kelas yang diinginkan
target_classes = ['cavallo', 'elefante', 'farfalla', 'gallina', 'gatto']
label_names = {'cavallo': 'kuda', 'elefante': 'gajah', 'farfalla': 'kupu-kupu', 'gallina': 'ayam', 'gatto': 'kucing'}

print(f"Jumlah kelas target: {len(target_classes)}")
print(f"Kelas yang diproses: {[label_names[c] for c in target_classes]}")

# Hitung gambar per kelas target
total_images = 0
print("\nJumlah gambar per kelas:")
for class_name in target_classes:
    class_path = os.path.join(raw_dir, class_name)
    if os.path.isdir(class_path):
        count = len([f for f in os.listdir(class_path) if f.lower().endswith(('.png', '.jpg', '.jpeg'))])
        print(f"  {label_names[class_name]} ({class_name}): {count} gambar")
        total_images += count
    else:
        print(f"  ⚠️ Folder {class_name} tidak ditemukan!")

print(f"\nTotal gambar dari kelas target: {total_images}")

"""### Data Preprocessing

#### Rename Label ke Bahasa Indonesia
"""

import os
import shutil

# Mapping nama kelas dari Bahasa Italia ke Bahasa Indonesia (Hanya 5 kelas target)
target_mapping = {
    'cavallo': 'kuda',
    'elefante': 'gajah',
    'farfalla': 'kupu-kupu',
    'gallina': 'ayam',
    'gatto': 'kucing'
}

raw_dir = 'dataset_raw/raw-img'

print("Mengubah nama folder target ke Bahasa Indonesia...")
for old_name, new_name in target_mapping.items():
    old_path = os.path.join(raw_dir, old_name)
    new_path = os.path.join(raw_dir, new_name)
    if os.path.exists(old_path):
        os.rename(old_path, new_path)
        print(f"  {old_name} -> {new_name} ✅")
    elif os.path.exists(new_path):
        print(f"  {new_name} (sudah tersedia) ✅")

# Menghapus folder yang tidak digunakan agar tidak ikut masuk ke model
print("\nMembersihkan folder kelas yang tidak digunakan...")
if os.path.exists(raw_dir):
    all_folders = os.listdir(raw_dir)
    for folder in all_folders:
        if folder not in target_mapping.values() and folder not in target_mapping.keys():
            folder_path = os.path.join(raw_dir, folder)
            if os.path.isdir(folder_path):
                shutil.rmtree(folder_path)
                print(f"  {folder} dihapus 🗑️")

# Verifikasi akhir
if os.path.exists(raw_dir):
    classes = sorted(os.listdir(raw_dir))
    print(f"\nKelas Final yang digunakan: {classes}")

"""#### Split Dataset"""

# >>Dataset dibagi dengan proposi 700% untuk training, 15% untuk Validation, dan 15% untuk Testing.
# Alasan logisnya adalah total dataset Animals-10 yang digunakan (setelah difilter menjadi 5 kelas)
# berjumlah besar (sekitar 10.000+ gambar).
# Proporsi 70% sudah sangat cukup bagi model untuk belajar mengekstraksi fitur tanpa kekurangan data,
# sementara prosi 15% (sekitar 1.600+ gambar) cukup representaatif untuk melakukan validasi dan pengujian yang valid.

# Split dataset menjadi train, validation, dan test (70%, 15%, 15%)
input_folder = 'dataset_raw/raw-img'
output_folder = 'dataset'

# Hapus folder output jika sudah ada
if os.path.exists(output_folder):
    shutil.rmtree(output_folder)

# Split dataset
splitfolders.ratio(
    input_folder,
    output=output_folder,
    seed=42,
    ratio=(0.7, 0.15, 0.15),  # train, val, test
    group_prefix=None
)

print("Dataset berhasil di-split!")
print(f"Train: 70%, Validation: 15%, Test: 15%")

# Verifikasi hasil split
train_dir = 'dataset/train'
val_dir = 'dataset/val'
test_dir = 'dataset/test'

def count_images(directory):
    total = 0
    for class_name in os.listdir(directory):
        class_path = os.path.join(directory, class_name)
        if os.path.isdir(class_path):
            count = len([f for f in os.listdir(class_path) if f.lower().endswith(('.png', '.jpg', '.jpeg'))])
            total += count
    return total

train_count = count_images(train_dir)
val_count = count_images(val_dir)
test_count = count_images(test_dir)

print(f"Training set: {train_count} gambar")
print(f"Validation set: {val_count} gambar")
print(f"Test set: {test_count} gambar")
print(f"Total: {train_count + val_count + test_count} gambar")

# Konfigurasi
IMG_SIZE = (224, 224)
BATCH_SIZE = 32

# Data Augmentation untuk training (moderate)
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,
    width_shift_range=0.15,
    height_shift_range=0.15,
    shear_range=0.15,
    zoom_range=0.15,
    horizontal_flip=True,
    brightness_range=[0.8, 1.2],
    fill_mode='nearest'
)

# Hanya rescale untuk validation dan test
val_test_datagen = ImageDataGenerator(rescale=1./255)

# Load data (Otomatis mendeteksi folder yang tersisa: kuda, gajah, kupu-kupu, ayam, kucing)
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

validation_generator = val_test_datagen.flow_from_directory(
    val_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

test_generator = val_test_datagen.flow_from_directory(
    test_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

# Simpan class names
class_names = sorted(list(train_generator.class_indices.keys()))
num_classes = len(class_names)
print(f"\nJumlah kelas terdeteksi: {num_classes}")
print(f"Nama kelas: {class_names}")

# Visualisasi sample gambar dari dataset
plt.figure(figsize=(15, 10))

# Ambil satu batch dari training data
images, labels = next(train_generator)

for i in range(12):
    plt.subplot(3, 4, i+1)
    plt.imshow(images[i])
    label_idx = np.argmax(labels[i])
    plt.title(class_names[label_idx], fontsize=12, fontweight='bold')
    plt.axis('off')

plt.suptitle('Sample Gambar dari Dataset Animals-10 (Label Indonesia)', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""## Membangun Model (CNN From Scratch)"""

# Membangun Model CNN Sequential yang lebih dalam
model = Sequential([
    # Block 1
    Conv2D(64, (3, 3), activation='relu', padding='same', input_shape=(224, 224, 3)),
    BatchNormalization(),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(2, 2),
    Dropout(0.25),

    # Block 2
    Conv2D(128, (3, 3), activation='relu', padding='same'),
    BatchNormalization(),
    Conv2D(128, (3, 3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(2, 2),
    Dropout(0.25),

    # Block 3
    Conv2D(256, (3, 3), activation='relu', padding='same'),
    BatchNormalization(),
    Conv2D(256, (3, 3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(2, 2),
    Dropout(0.25),

    # Block 4
    Conv2D(512, (3, 3), activation='relu', padding='same'),
    BatchNormalization(),
    Conv2D(512, (3, 3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(2, 2),
    Dropout(0.25),

    # Global Average Pooling (lebih efisien dari Flatten)
    GlobalAveragePooling2D(),

    # Fully Connected Layers
    Dense(512, activation='relu'),
    BatchNormalization(),
    Dropout(0.5),
    Dense(256, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

# Compile model
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Summary model
model.summary()

"""## Training Model CNN (From Scratch)

**EarlyStopping:** Mencegah model mengalami overfitting dan menghemat waktu komputasi dengan cara menghentikan proses training secara otomatis jika akurasi validasi tidak lagi mengalami peningkatan setelah beberapa epoch.

**ModelCheckpoint:** Berfungsi untuk menyimpan secara otomatis bobot (weights) model yang memiliki performa paling baik selama proses training berlangsung.

**ReduceLROnPlateau:** Membantu model untuk menemukan titik optimal yang lebih presisi dengan cara menurunkan nilai learning rate ketika kurva metrik (seperti loss) mulai stagnan (mendatar).
"""

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

# Callbacks
callbacks = [
    EarlyStopping(
        monitor='val_accuracy',
        patience=8,
        restore_best_weights=True,
        verbose=1
    ),
    ModelCheckpoint(
        'best_model.keras',
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.2,
        patience=5,
        min_lr=1e-7,
        verbose=1
    )
]

# Training
EPOCHS = 50

history = model.fit(
    train_generator,
    epochs=EPOCHS,
    validation_data=validation_generator,
    callbacks=callbacks,
    verbose=1
)

from google.colab import drive
drive.mount('/content/drive')

"""## Evaluasi dan Visualisasi"""

# Plot Akurasi dan Loss
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Plot Akurasi

axes[0].plot(history.history['accuracy'], label='Akurasi Training', color='blue', linewidth=2)
axes[0].plot(history.history['val_accuracy'], label='Akurasi Validasi', color='orange', linewidth=2)
axes[0].set_title('Akurasi Model', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Akurasi')
axes[0].legend(loc='lower right')
axes[0].grid(True, alpha=0.3)
axes[0].set_ylim([0, 1])

# Plot Loss
axes[1].plot(history.history['loss'], label='Loss Training', color='blue', linewidth=2)
axes[1].plot(history.history['val_loss'], label='Loss Validasi', color='orange', linewidth=2)
axes[1].set_title('Loss Model', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Loss')
axes[1].legend(loc='upper right')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('training_history.png', dpi=150)
plt.show()

print("Plot disimpan sebagai 'training_history.png'")

# Evaluasi pada Training Set (tanpa augmentasi)
train_eval_generator = val_test_datagen.flow_from_directory(
    train_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

train_loss, train_accuracy = model.evaluate(train_eval_generator, verbose=1)
print(f"\n{'='*50}")
print(f"Training Set Accuracy: {train_accuracy*100:.2f}%")
print(f"Training Set Loss: {train_loss:.4f}")

# Evaluasi pada Test Set
test_loss, test_accuracy = model.evaluate(test_generator, verbose=1)
print(f"\n{'='*50}")
print(f"Test Set Accuracy: {test_accuracy*100:.2f}%")
print(f"Test Set Loss: {test_loss:.4f}")
print(f"{'='*50}")

# Verifikasi kriteria
print(f"\n{'='*50}")
print("VERIFIKASI KRITERIA:")
print(f"{'='*50}")
if train_accuracy >= 0.85:
    print(f"✅ Training Accuracy >= 85%: PASSED ({train_accuracy*100:.2f}%)")
else:
    print(f"❌ Training Accuracy >= 85%: FAILED ({train_accuracy*100:.2f}%)")

if test_accuracy >= 0.85:
    print(f"✅ Test Accuracy >= 85%: PASSED ({test_accuracy*100:.2f}%)")
else:
    print(f"❌ Test Accuracy >= 85%: FAILED ({test_accuracy*100:.2f}%)")

"""## Transfer Learning dengan MobileNetV2

Sekarang kita akan mencoba menggunakan arsitektur pre-trained MobileNetV2 untuk melihat apakah performa model dapat ditingkatkan lebih jauh.
"""

from tensorflow.keras.applications import MobileNetV2

# 1. Load base model
base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)

# 2. Freeze base model
base_model.trainable = False

# 3. Bangun model di atas base model
mobilenet_model = Sequential([
    base_model,
    GlobalAveragePooling2D(),
    Dense(256, activation='relu'),
    BatchNormalization(),
    Dropout(0.4),
    Dense(num_classes, activation='softmax')
])

# 4. Compile
mobilenet_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

mobilenet_model.summary()

"""### Training MobileNetV2"""

callbacks_mobilenet = [
    EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True),
    ModelCheckpoint('best_mobilenet_model.keras', save_best_only=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=1e-6)
]

history_mobilenet = mobilenet_model.fit(
    train_generator,
    epochs=20,
    validation_data=validation_generator,
    callbacks=callbacks_mobilenet
)

# Evaluasi MobileNetV2 pada Test Set
test_loss_mn, test_acc_mn = mobilenet_model.evaluate(test_generator)
print(f"\nTest Accuracy (MobileNetV2): {test_acc_mn*100:.2f}%")

"""### Visualisasi Training MobileNetV2"""

# Plot Akurasi dan Loss - MobileNetV2
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(history_mobilenet.history['accuracy'], label='Akurasi Training', color='blue', linewidth=2)
axes[0].plot(history_mobilenet.history['val_accuracy'], label='Akurasi Validasi', color='orange', linewidth=2)
axes[0].set_title('Akurasi Model - MobileNetV2', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Akurasi')
axes[0].legend(loc='lower right')
axes[0].grid(True, alpha=0.3)
axes[0].set_ylim([0, 1])

axes[1].plot(history_mobilenet.history['loss'], label='Loss Training', color='blue', linewidth=2)
axes[1].plot(history_mobilenet.history['val_loss'], label='Loss Validasi', color='orange', linewidth=2)
axes[1].set_title('Loss Model - MobileNetV2', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Loss')
axes[1].legend(loc='upper right')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Plot Akurasi dan Loss
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Plot Akurasi

axes[0].plot(history.history['accuracy'], label='Akurasi Training', color='blue', linewidth=2)
axes[0].plot(history.history['val_accuracy'], label='Akurasi Validasi', color='orange', linewidth=2)
axes[0].set_title('Akurasi Model', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Akurasi')
axes[0].legend(loc='lower right')
axes[0].grid(True, alpha=0.3)
axes[0].set_ylim([0, 1])

# Plot Loss
axes[1].plot(history.history['loss'], label='Loss Training', color='blue', linewidth=2)
axes[1].plot(history.history['val_loss'], label='Loss Validasi', color='orange', linewidth=2)
axes[1].set_title('Loss Model', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Loss')
axes[1].legend(loc='upper right')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('training_history.png', dpi=150)
plt.show()

print("Plot disimpan sebagai 'training_history.png'")

# Evaluasi pada Training Set (tanpa augmentasi)
train_eval_generator = val_test_datagen.flow_from_directory(
    train_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

train_loss, train_accuracy = model.evaluate(train_eval_generator, verbose=1)
print(f"\n{'='*50}")
print(f"Training Set Accuracy: {train_accuracy*100:.2f}%")
print(f"Training Set Loss: {train_loss:.4f}")

# Evaluasi pada Test Set
test_loss, test_accuracy = model.evaluate(test_generator, verbose=1)
print(f"\n{'='*50}")
print(f"Test Set Accuracy: {test_accuracy*100:.2f}%")
print(f"Test Set Loss: {test_loss:.4f}")
print(f"{'='*50}")

# Verifikasi kriteria
print(f"\n{'='*50}")
print("VERIFIKASI KRITERIA:")
print(f"{'='*50}")
if train_accuracy >= 0.85:
    print(f"✅ Training Accuracy >= 85%: PASSED ({train_accuracy*100:.2f}%)")
else:
    print(f"❌ Training Accuracy >= 85%: FAILED ({train_accuracy*100:.2f}%)")

if test_accuracy >= 0.85:
    print(f"✅ Test Accuracy >= 85%: PASSED ({test_accuracy*100:.2f}%)")
else:
    print(f"❌ Test Accuracy >= 85%: FAILED ({test_accuracy*100:.2f}%)")

"""## Evaluasi Akhir & Confusion Matrix"""

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

# Reset generator agar prediksi dari awal
test_generator.reset()

for nama_model, mdl in [("CNN From Scratch", model), ("MobileNetV2", mobilenet_model)]:
    print(f"\n{'='*55}")
    print(f"  EVALUASI: {nama_model}")
    print(f"{'='*55}")

    test_generator.reset()
    y_pred_prob = mdl.predict(test_generator, verbose=0)
    y_pred = np.argmax(y_pred_prob, axis=1)
    y_true = test_generator.classes

    # Classification Report
    print(classification_report(y_true, y_pred, target_names=class_names))

    # Confusion Matrix
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(7, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names)
    plt.title(f'Confusion Matrix — {nama_model}', fontweight='bold')
    plt.ylabel('Label Aktual')
    plt.xlabel('Label Prediksi')
    plt.tight_layout()
    plt.show()

"""CNN From Scratch dan MobileNetV2 sama-sama dapat dikategorikan sebagai Good Fit. Pada CNN, kurva training accuracy dan validation accuracy bergerak cukup berdekatan dan sama-sama berada di atas 85%. Akurasi pelatihan mencapai sekitar 94,75%, sedangkan akurasi validasi terbaik mencapai 91,70%. Meskipun terdapat sedikit selisih dan fluktuasi pada beberapa epoch, kondisi tersebut belum menunjukkan overfitting yang berat.

MobileNetV2 juga menunjukkan kondisi Good Fit yang lebih stabil. Pada akhir pelatihan, training accuracy mencapai sekitar 98,37% dan validation accuracy 98,11%. Kedua kurva sangat berdekatan dan meningkat pada tingkat akurasi yang tinggi, sehingga menunjukkan kemampuan generalisasi yang baik.

Dengan demikian, tidak ada model yang mengalami overfitting berdasarkan kriteria tersebut, karena tidak ditemukan kondisi ketika training accuracy mendekati 100% sementara validation accuracy tertahan di bawah 80%. Namun, CNN memiliki generalization gap yang sedikit lebih besar dibandingkan MobileNetV2, sehingga MobileNetV2 menunjukkan pola pembelajaran yang lebih stabil.

## Konversi Model
"""

# 1. Simpan sebagai SavedModel
saved_model_path = 'saved_model'
model.export(saved_model_path)
print(f"✅ Model disimpan dalam format SavedModel di: {saved_model_path}/")

# Verifikasi SavedModel
# Note: model.export() creates a SavedModel directory, not a single file.
# To load it, we use tf.keras.models.load_model with the directory path.
loaded_model = keras.layers.TFSMLayer(saved_model_path, call_endpoint='serve')
print(f"   SavedModel berhasil di-load sebagai TFSMLayer.")

# 2. Konversi ke TensorFlow Lite
tflite_model_path = 'model.tflite'

# Konversi
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_path)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

# Simpan
with open(tflite_model_path, 'wb') as f:
    f.write(tflite_model)

# Verifikasi ukuran file
tflite_size = os.path.getsize(tflite_model_path) / (1024 * 1024)
print(f"✅ Model disimpan dalam format TF-Lite: {tflite_model_path}")
print(f"   Ukuran file: {tflite_size:.2f} MB")

# 3. Konversi ke TensorFlow.js
tfjs_model_path = 'tfjs_model'

!tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model {saved_model_path} {tfjs_model_path}

print(f"\n✅ Model disimpan dalam format TFJS di: {tfjs_model_path}/")

# List file TFJS
print("   Files:")
for f in os.listdir(tfjs_model_path):
    size = os.path.getsize(os.path.join(tfjs_model_path, f)) / 1024
    print(f"   - {f} ({size:.2f} KB)")

# Verifikasi semua format tersimpan
print("="*60)
print("VERIFIKASI SEMUA FORMAT MODEL")
print("="*60)

# SavedModel
if os.path.exists(saved_model_path) and os.path.isdir(saved_model_path):
    print(f"✅ SavedModel: {saved_model_path}/")
else:
    print(f"❌ SavedModel tidak ditemukan")

# TF-Lite
if os.path.exists(tflite_model_path):
    print(f"✅ TF-Lite: {tflite_model_path} ({os.path.getsize(tflite_model_path)/(1024*1024):.2f} MB)")
else:
    print(f"❌ TF-Lite tidak ditemukan")

# TFJS
if os.path.exists(tfjs_model_path) and os.path.isdir(tfjs_model_path):
    print(f"✅ TFJS: {tfjs_model_path}/")
else:
    print(f"❌ TFJS tidak ditemukan")

print("="*60)

"""## Inferensi Model / Uji Coba Model"""

# ============================================================
# PERBANDINGAN INFERENCE: CNN FROM SCRATCH vs MobileNetV2
# Menampilkan satu sampel dari setiap kelas dengan:
# 1. Gambar asli
# 2. Distribusi probabilitas CNN
# 3. Distribusi probabilitas MobileNetV2
# 4. Tabel ringkasan prediksi
# ============================================================

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image

# Ekstensi gambar yang didukung
VALID_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.bmp', '.webp'}

def prepare_image(img_path):
    """
    Memuat dan menyiapkan satu gambar agar sesuai dengan preprocessing
    yang digunakan saat training CNN dan MobileNetV2.

    Catatan:
    Notebook ini melatih kedua model dengan normalisasi 1/255,
    sehingga preprocessing inference juga menggunakan skala yang sama.
    """
    display_img = image.load_img(img_path, target_size=IMG_SIZE)
    img_array = image.img_to_array(display_img).astype(np.float32)
    img_array = np.expand_dims(img_array, axis=0) / 255.0
    return display_img, img_array


def predict_probabilities(img_array, trained_model):
    """Menghasilkan probabilitas, kelas prediksi, dan confidence."""
    probabilities = trained_model.predict(img_array, verbose=0)[0]
    predicted_index = int(np.argmax(probabilities))
    predicted_class = class_names[predicted_index]
    confidence = float(probabilities[predicted_index] * 100)
    return probabilities, predicted_class, confidence


def select_test_samples(test_directory, labels, samples_per_class=1, seed=42):
    """
    Memilih sampel secara reproducible dari setiap kelas.
    Berbeda dari os.listdir() biasa, urutan kelas dan gambar dibuat stabil.
    """
    rng = np.random.default_rng(seed)
    selected = []

    for label in labels:
        class_dir = Path(test_directory) / label
        image_files = sorted([
            path for path in class_dir.iterdir()
            if path.is_file() and path.suffix.lower() in VALID_EXTENSIONS
        ])

        if not image_files:
            print(f"⚠ Tidak ditemukan gambar pada kelas: {label}")
            continue

        number_to_select = min(samples_per_class, len(image_files))
        selected_indices = rng.choice(
            len(image_files),
            size=number_to_select,
            replace=False
        )

        for index in np.atleast_1d(selected_indices):
            selected.append((label, image_files[int(index)]))

    return selected


def plot_probability_distribution(
    axis,
    probabilities,
    predicted_class,
    actual_class,
    model_name
):
    """Membuat grafik probabilitas horizontal untuk satu model."""
    probabilities_percent = probabilities * 100
    y_positions = np.arange(len(class_names))

    bars = axis.barh(y_positions, probabilities_percent)
    axis.set_yticks(y_positions)
    axis.set_yticklabels([name.title() for name in class_names])
    axis.invert_yaxis()
    axis.set_xlim(0, 100)
    axis.set_xlabel("Probabilitas (%)")
    axis.grid(axis="x", linestyle="--", alpha=0.30)

    is_correct = predicted_class == actual_class
    status = "BENAR ✓" if is_correct else "SALAH ✗"
    confidence = np.max(probabilities_percent)

    axis.set_title(
        f"{model_name}\n"
        f"Prediksi: {predicted_class.title()} | "
        f"Confidence: {confidence:.2f}% | {status}",
        fontsize=11,
        fontweight="bold"
    )

    # Tampilkan nilai probabilitas pada setiap batang.
    for bar, value in zip(bars, probabilities_percent):
        text_x = min(value + 1.0, 96.0)
        axis.text(
            text_x,
            bar.get_y() + bar.get_height() / 2,
            f"{value:.1f}%",
            va="center",
            fontsize=9
        )

    # Tandai kelas aktual dengan teks tambahan.
    actual_index = class_names.index(actual_class)
    axis.get_yticklabels()[actual_index].set_fontweight("bold")


# Pilih satu gambar dari masing-masing kelas.
# Ubah samples_per_class menjadi 2 jika ingin menampilkan dua sampel per kelas.
test_samples = select_test_samples(
    test_directory=test_dir,
    labels=class_names,
    samples_per_class=1,
    seed=42
)

if not test_samples:
    raise ValueError("Tidak ada gambar uji yang ditemukan.")

# Simpan hasil untuk tabel ringkasan.
comparison_results = []

# Satu baris untuk setiap gambar:
# kolom 1 = gambar asli, kolom 2 = probabilitas CNN,
# kolom 3 = probabilitas MobileNetV2.
number_of_samples = len(test_samples)
figure = plt.figure(figsize=(18, 3.4 * number_of_samples))
grid = figure.add_gridspec(
    nrows=number_of_samples,
    ncols=3,
    width_ratios=[1.05, 1.55, 1.55],
    hspace=0.65,
    wspace=0.35
)

for row_index, (actual_class, img_path) in enumerate(test_samples):
    display_img, img_array = prepare_image(img_path)

    cnn_prob, cnn_pred, cnn_conf = predict_probabilities(
        img_array,
        model
    )
    mn_prob, mn_pred, mn_conf = predict_probabilities(
        img_array,
        mobilenet_model
    )

    # Kolom gambar asli
    image_axis = figure.add_subplot(grid[row_index, 0])
    image_axis.imshow(display_img)
    image_axis.axis("off")
    image_axis.set_title(
        f"Sampel {row_index + 1}\n"
        f"Label Aktual: {actual_class.title()}",
        fontsize=11,
        fontweight="bold"
    )
    image_axis.text(
        0.5,
        -0.08,
        img_path.name,
        transform=image_axis.transAxes,
        ha="center",
        va="top",
        fontsize=8
    )

    # Kolom hasil CNN
    cnn_axis = figure.add_subplot(grid[row_index, 1])
    plot_probability_distribution(
        cnn_axis,
        cnn_prob,
        cnn_pred,
        actual_class,
        "CNN From Scratch"
    )

    # Kolom hasil MobileNetV2
    mn_axis = figure.add_subplot(grid[row_index, 2])
    plot_probability_distribution(
        mn_axis,
        mn_prob,
        mn_pred,
        actual_class,
        "MobileNetV2"
    )

    comparison_results.append({
        "Nama File": img_path.name,
        "Label Aktual": actual_class.title(),
        "Prediksi CNN": cnn_pred.title(),
        "Confidence CNN (%)": round(cnn_conf, 2),
        "CNN Benar": "Ya" if cnn_pred == actual_class else "Tidak",
        "Prediksi MobileNetV2": mn_pred.title(),
        "Confidence MobileNetV2 (%)": round(mn_conf, 2),
        "MobileNetV2 Benar": "Ya" if mn_pred == actual_class else "Tidak"
    })

figure.suptitle(
    "Perbandingan Inference CNN From Scratch dan MobileNetV2\n"
    "Dataset Uji Animals-10",
    fontsize=17,
    fontweight="bold",
    y=1.01
)

plt.show()

# Tabel ringkasan hasil inference.
comparison_df = pd.DataFrame(comparison_results)

print("\n" + "=" * 90)
print("RINGKASAN PERBANDINGAN INFERENCE")
print("=" * 90)
display(comparison_df)

# Ringkasan hanya berlaku untuk sampel yang ditampilkan,
# bukan pengganti hasil evaluasi seluruh test set.
cnn_sample_correct = (comparison_df["CNN Benar"] == "Ya").sum()
mn_sample_correct = (comparison_df["MobileNetV2 Benar"] == "Ya").sum()

print(
    f"\nCNN From Scratch benar pada "
    f"{cnn_sample_correct}/{len(comparison_df)} sampel yang ditampilkan."
)
print(
    f"MobileNetV2 benar pada "
    f"{mn_sample_correct}/{len(comparison_df)} sampel yang ditampilkan."
)
print(
    "\nCatatan: hasil di atas merupakan demonstrasi inference pada sampel terpilih. "
    "Akurasi resmi tetap harus menggunakan evaluasi seluruh test set."
)

# TF-Lite Inference Test
print("Testing TF-Lite Model...")

# Load TFLite model
interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test dengan gambar pertama
if test_samples:
    # Use the image path from the first sample in test_samples
    img_path_for_tflite = test_samples[0][1]
    img = image.load_img(img_path_for_tflite, target_size=IMG_SIZE)
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0).astype(np.float32)
    img_array = img_array / 255.0

    interpreter.set_tensor(input_details[0]['index'], img_array)
    interpreter.invoke()

    tflite_predictions = interpreter.get_tensor(output_details[0]['index'])
    tflite_predicted_class = class_names[np.argmax(tflite_predictions[0])]
    tflite_confidence = np.max(tflite_predictions[0]) * 100

    print(f"✅ TF-Lite Prediction: {tflite_predicted_class} ({tflite_confidence:.1f} %)")
    print(f"   TF-Lite model berfungsi dengan baik!")
else:
    print("Tidak ada gambar sampel yang tersedia untuk pengujian TF-Lite model.")

# Download semua model
from google.colab import files
import shutil

# Zip semua model
print("Membuat archive untuk download...")

# Zip SavedModels
shutil.make_archive('saved_model', 'zip', '.', 'saved_model')
print("✅ saved_model.zip created")

# Zip TFJS
shutil.make_archive('tfjs_model', 'zip', '.', 'tfjs_model')
print("✅ tfjs_model.zip created")

# Buat requirements.txt
print("\nMembuat requirements.txt...")
requirements = [
    'tensorflow==2.19.0',
    'tensorflowjs',
    'split-folders',
    'numpy',
    'matplotlib'
]
with open('requirements.txt', 'w') as f:
    for req in requirements:
        f.write(req + '\n')
print("✅ requirements.txt created")

print("\n" + "="*50)
print("Files ready for download:")
print("- saved_model.zip")
print("- model.tflite")
print("- tfjs_model.zip")
print("- requirements.txt")
print("="*50)

# Uncomment untuk auto-download
files.download('saved_model.zip')
files.download('model.tflite')
files.download('tfjs_model.zip')
files.download('requirements.txt')